
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; img-src * data:; media-src *"


[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[functions]
directory = "regalsway/frontend"
runtime = "nodejs14.x"
