[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; img-src * data:; media-src *"


[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[functions]
  external_node_modules = ["package-1"]
  included_files = ["files/*.md"]
